export const GET_ALL_SUPPLIERS_REQUEST = 'GET_ALL_SUPPLIERS_REQUEST'
export const GET_ALL_SUPPLIERS_SUCCESS = 'GET_ALL_SUPPLIERS_SUCCESS'
export const GET_ALL_SUPPLIERS_FAILURE = 'GET_ALL_SUPPLIERS_FAILURE'

export const ADD_SUPPLIER_REQUEST = 'ADD_SUPPLIER_REQUEST'
export const ADD_SUPPLIER_SUCCESS = 'ADD_SUPPLIER_SUCCESS'
export const ADD_SUPPLIER_FAILURE = 'ADD_SUPPLIER_FAILURE'

export const UPDATE_SUPPLIER_REQUEST = 'UPDATE_SUPPLIER_REQUEST'
export const UPDATE_SUPPLIER_SUCCESS = 'UPDATE_SUPPLIER_SUCCESS'
export const UPDATE_SUPPLIER_FAILURE = 'UPDATE_SUPPLIER_FAILURE'
