export const GET_INVENTORY_REPORT_REQUEST = 'GET_INVENTORY_REPORT_REQUEST'
export const GET_INVENTORY_REPORT_SUCCESS = 'GET_INVENTORY_REPORT_SUCCESS'
export const GET_INVENTORY_REPORT_FAILURE = 'GET_INVENTORY_REPORT_FAILURE'