export const CREATE_TRANSACTION_REQUEST = "CREATE_TRANSACTION_REQUEST"
export const CREATE_TRANSACTION_SUCCESS = "CREATE_TRANSACTION_SUCCESS"
export const CREATE_TRANSACTION_FAILURE = "CREATE_TRANSACTION_FAILURE"

export const UPDATE_TRANSACTION_REQUEST = "UPDATE_TRANSACTION_REQUEST"
export const UPDATE_TRANSACTION_SUCCESS = "UPDATE_TRANSACTION_SUCCESS"
export const UPDATE_TRANSACTION_FAILURE = "UPDATE_TRANSACTION_FAILURE"

export const GET_ALL_TRANSACTION_REQUEST = "GET_ALL_TRANSACTION_REQUEST"
export const GET_ALL_TRANSACTION_SUCCESS = "GET_ALL_TRANSACTION_SUCCESS"
export const GET_ALL_TRANSACTION_FAILURE = "GET_ALL_TRANSACTION_FAILURE"
