export const GET_ALL_PUBLISHER_REQUEST = 'GET_ALL_PUBLISHER_REQUEST'
export const GET_ALL_PUBLISHER_SUCCESS = 'GET_ALL_PUBLISHER_SUCCESS'
export const GET_ALL_PUBLISHER_FAILURE = 'GET_ALL_PUBLISHER_FAILURE'

