export const GET_MONTHLY_TRANSACTION_REQUEST = "GET_MONTHLY_TRANSACTION_REQUEST"
export const GET_MONTHLY_TRANSACTION_SUCCESS = "GET_MONTHLY_TRANSACTION_SUCCESS"
export const GET_MONTHLY_TRANSACTION_FAILURE = "GET_MONTHLY_TRANSACTION_FAILURE"

export const GET_ACCHIEVEMENT_STATISTIC_REQUEST = "GET_ACCHIEVEMENT_STATISTIC_REQUEST"
export const GET_ACCHIEVEMENT_STATISTIC_SUCCESS = "GET_ACCHIEVEMENT_STATISTIC_SUCCESS"
export const GET_ACCHIEVEMENT_STATISTIC_FAILURE = "GET_ACCHIEVEMENT_STATISTIC_FAILURE"

export const GET_TOP_SELLING_BOOKS_REQUEST = "GET_TOP_SELLING_BOOKS_REQUEST"
export const GET_TOP_SELLING_BOOKS_SUCCESS = "GET_TOP_SELLING_BOOKS_SUCCESS"
export const GET_TOP_SELLING_BOOKS_FAILURE = "GET_TOP_SELLING_BOOKS_FAILURE"




