export const GET_ALL_AUTHOR_REQUEST = 'GET_ALL_AUTHOR_REQUEST'
export const GET_ALL_AUTHOR_SUCCESS = 'GET_ALL_AUTHOR_SUCCESS'
export const GET_ALL_AUTHOR_FAILURE = 'GET_ALL_AUTHOR_FAILURE'

export const ADD_AUTHOR_REQUEST = 'ADD_AUTHOR_REQUEST'
export const ADD_AUTHOR_SUCCESS = 'ADD_AUTHOR_SUCCESS'
export const ADD_AUTHOR_FAILURE = 'ADD_AUTHOR_FAILURE'

export const UPDATE_AUTHOR_REQUEST = 'UPDATE_AUTHOR_REQUEST'
export const UPDATE_AUTHOR_SUCCESS = 'UPDATE_AUTHOR_SUCCESS'
export const UPDATE_AUTHOR_FAILURE = 'UPDATE_AUTHOR_FAILURE'