export const ADD_BOOK_REQUEST = 'ADD_BOOK_REQUEST'
export const ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS'
export const ADD_BOOK_FAILURE = 'ADD_BOOK_FAILURE'

export const GET_ALL_BOOK_REQUEST = 'GET_ALL_BOOK_REQUEST'
export const GET_ALL_BOOK_SUCCESS = 'GET_ALL_BOOK_SUCCESS'
export const GET_ALL_BOOK_FAILURE = 'GET_ALL_BOOK_FAILURE'


export const FIND_BOOK_BY_ID_REQUEST = 'FIND_BOOK_BY_ID_REQUEST'
export const FIND_BOOK_BY_ID_SUCCESS = 'FIND_BOOK_BY_ID_SUCCESS'
export const FIND_BOOK_BY_ID_FAILURE = 'FIND_BOOK_BY_ID_FAILURE'

export const UPDATE_BOOK_REQUEST = 'UPDATE_BOOK_REQUEST'
export const UPDATE_BOOK_SUCCESS = 'UPDATE_BOOK_SUCCESS'
export const UPDATE_BOOK_FAILURE = 'UPDATE_BOOK_FAILURE'