export const GET_ALL_STAFF_REQUEST = 'GET_ALL_STAFF_REQUEST'
export const GET_ALL_STAFF_SUCCESS = 'GET_ALL_STAFF_SUCCESS'
export const GET_ALL_STAFF_FAILURE = 'GET_ALL_STAFF_FAILURE'

export const ADD_STAFF_REQUEST = 'ADD_STAFF_REQUEST'
export const ADD_STAFF_SUCCESS = 'ADD_STAFF_SUCCESS'
export const ADD_STAFF_FAILURE = 'ADD_STAFF_FAILURE'

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE'

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE'

