export const CREATE_TRANSACTION_REQ_REQUEST = "CREATE_TRANSACTION_REQ_REQUEST"
export const CREATE_TRANSACTION_REQ_SUCCESS = "CREATE_TRANSACTION_REQ_SUCCESS"
export const CREATE_TRANSACTION_REQ_FAILURE = "CREATE_TRANSACTION_REQ_FAILURE"

export const UPDATE_TRANSACTION_REQ_REQUEST = "UPDATE_TRANSACTION_REQ_REQUEST"
export const UPDATE_TRANSACTION_REQ_SUCCESS = "UPDATE_TRANSACTION_REQ_SUCCESS"
export const UPDATE_TRANSACTION_REQ_FAILURE = "UPDATE_TRANSACTION_REQ_FAILURE"

export const GET_ALL_TRANSACTION_REQ_REQUEST = "GET_ALL_TRANSACTION_REQ_REQUEST"
export const GET_ALL_TRANSACTION_REQ_SUCCESS = "GET_ALL_TRANSACTION_REQ_SUCCESS"
export const GET_ALL_TRANSACTION_REQ_FAILURE = "GET_ALL_TRANSACTION_REQ_FAILURE"

export const APPROVE_TRANSACTION_REQ_REQUEST = "APPROVE_TRANSACTION_REQ_REQUEST"
export const APPROVE_TRANSACTION_REQ_SUCCESS = "APPROVE_TRANSACTION_REQ_SUCCESS"
export const APPROVE_TRANSACTION_REQ_FAILURE = "APPROVE_TRANSACTION_REQ_FAILURE"

export const REJECT_TRANSACTION_REQ_REQUEST = "REJECT_TRANSACTION_REQ_REQUEST"
export const REJECT_TRANSACTION_REQ_SUCCESS = "REJECT_TRANSACTION_REQ_SUCCESS"
export const REJECT_TRANSACTION_REQ_FAILURE = "REJECT_TRANSACTION_REQ_FAILURE"